import openai
import re




def generate_Authors(company,number, api_key_GPT):
      
    '''
    Creation of the authors list
    '''
    #Token Inizialization
    openai.api_key = api_key_GPT

    query = f'Can you give me some full name in total just {number} persons, that could work in a {company} company? Print them as a list 1. fullname etc..'

    full_message = []
    full_message.append({'role': 'user', 'content': query})

    names = authors_from_Chat_GPT(full_message)
    

    return names



def authors_from_Chat_GPT(prompt, model="gpt-3.5-turbo"):
        response = openai.ChatCompletion.create(
            model=model,
            messages=prompt,
            max_tokens=300,
            n=1,
            stop=None,
            temperature=1.3,#Temperature is a parameter that controls the “creativity” or randomness of the text generated by GPT-3.5.
            #The range can be [0.5-2.0], suggest 1.3
        )

        message = response.choices[0].message.content.strip()
  
        name_pattern = r"\b[A-Z][a-z]+\s[A-Z][a-z]+\b"

        # Find all occurrences of names in the text
        names = re.findall(name_pattern, message)
        
        unique_names = list(set(names))

        print(unique_names)

        return unique_names 

